name: 'Generate Date and Time'
description: 'A GitHub Action to get the current date and time from an Azure Function'
inputs:
  function-url:
    description: 'The URL to fetch the current date and time from'
    required: true
  function-key:
    description: 'The key to access the Azure Function'
    required: true
outputs:
  currentDateTime:
    description: 'The current date and time from Azure Function'
runs:
  using: 'node20'
  main: 'index.js'
